services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    hostname: timescaledb
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=booksdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - timescaledb

  bookapi:
    build:
      context: ../BookApi
      dockerfile: Dockerfile
    container_name: bookapi
    hostname: bookapi
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=timescaledb;Port=5432;Database=booksdb;Username=admin;Password=admin123;TimeZone=UTC
    depends_on:
      - timescaledb

  bookapi-mcp-server:
    build:
      context: ../book-api-mcp-server-dotnet
      dockerfile: Dockerfile
    container_name: bookapi-mcp-server
    hostname: bookapi-mcp-server
    environment:
      - BookApi__BaseUrl=http://bookapi:8080
    depends_on:
      - bookapi

volumes:
  postgres-data:
  pgadmin_data: