apiVersion: v1
kind: ConfigMap
metadata:
  name: bookapi-config
data:
  ConnectionStrings__DefaultConnection: "Host=timescaledb;Port=5432;Database=booksdb;Username=admin;Password=admin123;TimeZone=UTC"

