apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-envoy-config
  namespace: default
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          protocol: TCP
          address: 127.0.0.1
          port_value: 9901
    static_resources:
      listeners:
        # Inbound listener - receives traffic from other services
        - name: listener_inbound
          address:
            socket_address:
              protocol: TCP
              address: 0.0.0.0
              port_value: 15001
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: inbound_http
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: local_service
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: local_app
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              transport_socket:
                name: envoy.transport_sockets.tls
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                  require_client_certificate: true
                  common_tls_context:
                    tls_certificates:
                      - certificate_chain:
                          filename: /etc/envoy/certs/tls.crt
                        private_key:
                          filename: /etc/envoy/certs/tls.key
                    validation_context:
                      trusted_ca:
                        filename: /etc/envoy/certs/ca.crt
                      match_subject_alt_names:
                        - exact: envoy
                        - exact: envoy.default.svc.cluster.local
        # Outbound HTTP listener
        - name: listener_outbound_http
          address:
            socket_address:
              protocol: TCP
              address: 127.0.0.1
              port_value: 15006
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: outbound_http
                    route_config:
                      name: outbound_route
                      virtual_hosts:
                        - name: passthrough
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: passthrough
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        # Outbound TCP listener for database connections
        - name: listener_outbound_tcp
          address:
            socket_address:
              protocol: TCP
              address: 127.0.0.1
              port_value: 15007
          filter_chains:
            - filters:
                - name: envoy.filters.network.tcp_proxy
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    stat_prefix: outbound_tcp
                    cluster: timescaledb
      clusters:
        # Local application cluster
        - name: local_app
          connect_timeout: 0.25s
          type: STATIC
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: local_app
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 80
        # Cluster for timescaledb with mTLS (TCP proxy)
        - name: timescaledb
          connect_timeout: 0.5s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: timescaledb
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: timescaledb.default.svc.cluster.local
                          port_value: 15001
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: /etc/envoy/certs/tls.crt
                    private_key:
                      filename: /etc/envoy/certs/tls.key
                validation_context:
                  trusted_ca:
                    filename: /etc/envoy/certs/ca.crt
                  match_subject_alt_names:
                    - exact: timescaledb
                    - exact: timescaledb.default.svc.cluster.local
        # Passthrough cluster for outbound HTTP traffic
        - name: passthrough
          connect_timeout: 0.25s
          type: ORIGINAL_DST
          lb_policy: CLUSTER_PROVIDED
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: /etc/envoy/certs/tls.crt
                    private_key:
                      filename: /etc/envoy/certs/tls.key
                validation_context:
                  trusted_ca:
                    filename: /etc/envoy/certs/ca.crt

