apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapi-mcp-server
  labels:
    app: bookapi-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookapi-mcp-server
  template:
    metadata:
      labels:
        app: bookapi-mcp-server
    spec:
      containers:
        - name: bookapi-mcp-server
          image: us-central1-docker.pkg.dev/book-api-mcp-server/book-api-mcp-server-images/book-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5289
          envFrom:
            - configMapRef:
                name: bookapi-mcp-server-config
          readinessProbe:
            httpGet:
              path: /health
              port: 5289
              httpHeaders:
                - name: Mcp-Session-Id
                  value: readiness-probe
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5289
              httpHeaders:
                - name: Mcp-Session-Id
                  value: liveness-probe
            initialDelaySeconds: 30
            periodSeconds: 30